% =====================================================
% This script is used to generate undersampled binning masks
% according to the ET mask, where
% sampling rate of ET mask: 1ms
% sampling rate of readouts: TR=6.2ms / 8ms depending on sequence
% =====================================================
clearvars; clc;
addpath(genpath('/home/debi/jaime/repos/MR-EyeTrack/recon'));
addpath(genpath('/home/debi/jaime/repos/MR-EyeTrack/recon/Recon_scripts'));
addpath(genpath('/home/debi/yiwei/forclone/pulseq'));
addpath(genpath('/home/debi/MatTechLab/monalisa'));

%% Config

% Variables
subject_num = 2;
mask_type = 'clean';
undersampling_factor = 0.95;  % remove this ratio of preserved readouts
th_ratio = 0.75;

% Base paths (aligned with S2_eyeMask_t1_binning_pulseq.m)
baseDir = '/home/debi/jaime/repos/MR-EyeTrack/data/study';
subjectStr = sprintf('sub-%03d', subject_num);

subjectDir = fullfile(baseDir, subjectStr);
reconDir = fullfile(subjectDir, 'recon');
inputDir = fullfile(reconDir, 'bins', mask_type);
outputMaskType = sprintf('%s_%.2f', mask_type, undersampling_factor);
outputDir = fullfile(reconDir, 'bins', outputMaskType);

% Ensure output directory exists
if ~isfolder(outputDir)
    mkdir(outputDir);
    disp(['Directory created: ', outputDir]);
else
    disp(['Directory already exists: ', outputDir]);
end

if ~isfolder(inputDir)
    error('Input mask directory does not exist: %s', inputDir);
end

%% Random undersample

region_idx_list = 0:3;  % 0:up 1:down 2:left 3:right

for region_idx = region_idx_list
    % Load the mask generated by S2_eyeMask_t1_binning_pulseq.m
    inFileName = sprintf('eMask_th%.2f_region%i.mat', th_ratio, region_idx);
    eMaskFilePath = fullfile(inputDir, inFileName);

    if ~isfile(eMaskFilePath)
        warning('Mask file not found, skipping: %s', eMaskFilePath);
        continue;
    end

    loadedMask = load(eMaskFilePath);
    if isfield(loadedMask, 'eMaskN')
        eMaskN = loadedMask.eMaskN;
    else
        error('Expected variable eMaskN not found in %s', eMaskFilePath);
    end

    % Randomly set a proportion of 1-entries to 0
    oneIdx = find(eMaskN == 1);
    numToZero = floor(numel(oneIdx) * undersampling_factor);

    if numToZero > 0
        randOrder = randperm(numel(oneIdx), numToZero);
        idxToZero = oneIdx(randOrder);
        eMaskN(idxToZero) = 0;
    end

    % Convert to logical type for minimal memory usage
    eMaskN = logical(eMaskN);

    % Save the modified mask with the same naming pattern
    savePath = fullfile(outputDir, inFileName);
    save(savePath, 'eMaskN');
    disp(['Undersampled mask saved to: ', savePath]);
end
